version: "3"

services:

  backend:
    container_name: backend
    restart: 'on-failure'
    image: "gcr.io/code2duo/lenzo:latest"
    pull_policy: always
    env_file:
      - ./.env.dev
    links:
      - redis

  redis:
    container_name: "redis"
    image: "redis:alpine"

volumes:
  static_volume:
